export const siteConfig = {
  name: "Tam Custom Patches",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://tamcustompatches.com",
  description:
    "Premium custom patches, apparel, martial arts uniforms, and promotional products made for quote-first manufacturing projects.",
  email: "sales@tamcustompatches.com",
} as const;

export const routes = {
  home: "/",
  quote: "/quote",
  reorder: "/quote?intent=reorder",
  aiDesigner: "/ai-designer",
  customPatches: "/custom-patches",
  embroideredPatches: "/custom-patches/embroidered",
  pvcPatches: "/custom-patches/pvc",
  wovenPatches: "/custom-patches/woven",
  chenillePatches: "/custom-patches/chenille",
  printedPatches: "/custom-patches/printed",
  velcroPatches: "/custom-patches/velcro",
  apparel: "/apparel",
  tshirts: "/apparel/t-shirts",
  hoodies: "/apparel/hoodies",
  crewnecks: "/apparel/crewnecks",
  sweatshirts: "/apparel/sweatshirts",
  poloShirts: "/apparel/polo-shirts",
  tankTops: "/apparel/tank-tops",
  jerseys: "/apparel/jerseys",
  activewear: "/apparel/activewear",
  martialArts: "/martial-arts",
  bjjGis: "/martial-arts/bjj-gis",
  karateUniforms: "/martial-arts/karate-uniforms",
  taekwondoUniforms: "/martial-arts/taekwondo-uniforms",
  judoUniforms: "/martial-arts/judo-uniforms",
  martialArtsTrainingApparel: "/martial-arts/training-apparel",
  accessories: "/accessories",
  scoutNeckerchiefs: "/accessories/scout-neckerchiefs",
  embroideredKeychains: "/accessories/embroidered-keychains",
  pvcKeychains: "/accessories/pvc-keychains",
  stickers: "/accessories/stickers",
  industries: "/industries",
  militaryIndustry: "/industries/military",
  lawEnforcementIndustry: "/industries/law-enforcement",
  sportsTeamsIndustry: "/industries/sports-teams",
  schoolsIndustry: "/industries/schools-universities",
  scoutGroupsIndustry: "/industries/scout-groups",
  motorcycleClubsIndustry: "/industries/motorcycle-clubs",
  fashionBrandsIndustry: "/industries/fashion-brands",
  workwearIndustry: "/industries/workwear",
  eventsIndustry: "/industries/events",
  martialArtsClubsIndustry: "/industries/martial-arts-clubs",
  gallery: "/gallery",
  blog: "/blog",
  sizeGuide: "/resources/size-guide",
  faq: "/faq",
  shipping: "/shipping",
  about: "/about",
  contact: "/contact",
  privacy: "/privacy",
  terms: "/terms",
  accessibility: "/accessibility",
  sitemap: "/sitemap",
} as const;
