export const siteConfig = {
  name: "Tam Custom Patches",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://tamcustompatches.com",
  description:
    "Premium custom patches, apparel, martial arts uniforms, and promotional products made for quote-first manufacturing projects.",
  email: "sales@tamcustompatches.com",
} as const;

export const routes = {
  home: "/",
  products: "/products",
  quote: "/quote",
  reorder: "/quote?intent=reorder",
  aiDesigner: "/ai-designer",
  designYourOwnPatch: "/design-your-own-patch",
  customPatches: "/custom-patches",
  embroideredPatches: "/custom-patches/embroidered",
  pvcPatches: "/custom-patches/pvc",
  wovenPatches: "/custom-patches/woven",
  chenillePatches: "/custom-patches/chenille",
  printedPatches: "/custom-patches/printed",
  velcroPatches: "/custom-patches/velcro",
  apparel: "/apparel",
  tshirts: "/apparel/t-shirts",
  longSleeveShirts: "/apparel/t-shirts/long-sleeve",
  hoodies: "/apparel/hoodies",
  crewnecks: "/apparel/crewnecks",
  sweatshirts: "/apparel/sweatshirts",
  poloShirts: "/apparel/polo-shirts",
  tankTops: "/apparel/tank-tops",
  jerseys: "/apparel/jerseys",
  activewear: "/apparel/activewear",
  performanceTshirts: "/apparel/activewear/performance-t-shirts",
  trainingTops: "/apparel/activewear/training-tops",
  trainingShorts: "/apparel/activewear/training-shorts",
  tracksuits: "/apparel/activewear/tracksuits",
  sportsUniforms: "/apparel/activewear/sports-uniforms",
  martialArts: "/martial-arts",
  bjjGis: "/martial-arts/bjj-gis",
  judoGis: "/martial-arts/judo-uniforms",
  karateUniforms: "/martial-arts/karate-uniforms",
  taekwondoUniforms: "/martial-arts/taekwondo-uniforms",
  judoUniforms: "/martial-arts/judo-uniforms",
  rashGuards: "/martial-arts/rash-guards",
  fightShorts: "/martial-arts/fight-shorts",
  martialArtsTrainingApparel: "/martial-arts/training-apparel",
  martialArtsPatches: "/martial-arts/patches",
  accessories: "/accessories",
  scoutNeckerchiefs: "/accessories/scout-neckerchiefs",
  embroideredKeychains: "/accessories/embroidered-keychains",
  pvcKeychains: "/accessories/pvc-keychains",
  wovenLabels: "/accessories/woven-labels",
  stickers: "/accessories/stickers",
  hatPatches: "/accessories/hat-patches",
  customBadges: "/accessories/custom-badges",
  industries: "/industries",
  militaryIndustry: "/industries/military",
  lawEnforcementIndustry: "/industries/law-enforcement",
  policeDepartmentsIndustry: "/industries/police-departments",
  fireDepartmentsIndustry: "/industries/fire-departments",
  sportsTeamsIndustry: "/industries/sports-teams",
  schoolsIndustry: "/industries/schools-universities",
  scoutGroupsIndustry: "/industries/scout-groups",
  motorcycleClubsIndustry: "/industries/motorcycle-clubs",
  businessesIndustry: "/industries/businesses",
  fashionBrandsIndustry: "/industries/fashion-brands",
  workwearIndustry: "/industries/workwear",
  eventsIndustry: "/industries/events",
  martialArtsClubsIndustry: "/industries/martial-arts-clubs",
  martialArtsSchoolsIndustry: "/industries/martial-arts-schools-and-academies",
  clubsOrganizationsIndustry: "/industries/clubs-and-organizations",
  gallery: "/gallery",
  reviews: "/reviews",
  blog: "/blog",
  sizeGuide: "/resources/size-guide",
  patchSizeGuide: "/resources/patch-size-guide",
  artworkGuidelines: "/resources/artwork-guidelines",
  backingOptions: "/resources/backing-options",
  borderOptions: "/resources/border-options",
  colorGuide: "/resources/color-guide",
  howPricingWorks: "/resources/how-pricing-works",
  howItWorks: "/how-it-works",
  helpCenter: "/help-center",
  fileRequirements: "/resources/file-requirements",
  productionProcess: "/resources/production-process",
  faq: "/faq",
  shipping: "/shipping",
  about: "/about",
  whyChooseUs: "/about/why-choose-us",
  qualityStandards: "/about/quality-standards",
  ourProcess: "/about/our-process",
  contact: "/contact",
  privacy: "/privacy",
  terms: "/terms",
  accessibility: "/accessibility",
  sitemap: "/sitemap",
} as const;
